version: "3"

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  try:
    taskfile: ./crates/rs-try/
    dir: ./crates/rs-try/
    optional: true


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing
  WORKSPACE: "crates/"

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  dev:
    cmds:
      - rustup toolchain install nightly
      - rustup toolchain list

  ################################################################################


  # usage:
  #   - task n -- --lib tmp/demo1
  #   - task n -- --bin tmp/demo2
  new:
    aliases: [ "n" ]
    cmds:
      - cargo new {{.CLI_ARGS}}

  ################################################################################

  run:
    cmds:
      - cargo run


  ###########################################################################

  quick:
    aliases: [ "q" ]
    cmds:
      - task: commit
      - task: commit
      - git status
      - task: push
    ignore_error: true

  commit:
    aliases: [ "c" ]
    cmds:
      - git add .
      - git commit -m "update" --no-verify
    ignore_error: true


  pull:
    aliases: [ "pl" ]
    cmds:
      - git pull

  push:
    aliases: [ "p" ]
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
